### PR TITLE
add a simple UCI engine

### PR DESCRIPTION
**Pull request by robertnurnberg**
A simple local test with scid seems to work fine.

Feedback welcome.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
@gahtan-syarif for some reason fast-chess does not like this little engine. I put the following line into the file `cdb2uci.sh`:
```shell
python $HOME/git/cdblib/cdb2uci.py -c 1 -ee
```

and this works fine with scid, for example.

But when I run `rm -f cdblog.txt && ./fast-chess -engine cmd=../stockfish/src/stockfish name=sf -engine cmd=../cdblib/cdb2uci.sh name=cdb2uci -each tc=10+5 -concurrency 1 -openings file=grob.epd -log file=cdblog.txt level=trace -rounds 2 -games 1 -pgnout file=grob_sf_cdb2uci.pgn`, I get the following weird behaviour:
```
[TRACE ] [18:12:39.004422] <fastchess> Creating tournament...
[WARN  ] [18:12:39.004565] <fastchess> Warning: No opening book seed specified! Consider specifying one, otherwise the match will be played using the default seed of 951356066.
[TRACE ] [18:12:39.004582] <fastchess> Seeding random number generator with seed: 951356066
[TRACE ] [18:12:39.004728] <fastchess> Setting results...
[INFO  ] [18:12:39.004771] <fastchess> Indexing opening suite...
[TRACE ] [18:12:39.004783] <fastchess> Starting tournament...
[TRACE ] [18:12:39.004790] <fastchess> Starting round robin tournament...
[TRACE ] [18:12:39.004795] <fastchess> Starting tournament...
[TRACE ] [18:12:39.004800] <fastchess> Creating matches...
[TRACE ] [18:12:39.004948] <fastchess> Playing game 1 between sf and cdb2uci
[TRACE ] [18:12:39.005013] <139776393487936> fastchess --- Refreshing engine sf
[TRACE ] [18:12:39.005036] <139776393487936> fastchess --- Starting engine sf at ../stockfish/src/stockfish
[TRACE ] [18:12:39.005328] <139776393487936> fastchess --- Sending uci to engine sf
[Engine] [18:12:39.005355] <139776393487936> sf <--- uci
[TRACE ] [18:12:39.005378] <139776393487936> fastchess --- Waiting for uciok from engine sf
[Engine] [18:12:39.009492] <139776393487936> sf ---> Stockfish dev-20240705-2cbc20e8 by the Stockfish developers (see AUTHORS file)
[Engine] [18:12:39.244225] <139776393487936> sf ---> id name Stockfish dev-20240705-2cbc20e8
[Engine] [18:12:39.244251] <139776393487936> sf ---> id author the Stockfish developers (see AUTHORS file)
[Engine] [18:12:39.244258] <139776393487936> sf ---> option name Debug Log File type string default 
[Engine] [18:12:39.244265] <139776393487936> sf ---> option name NumaPolicy type string default auto
[Engine] [18:12:39.244271] <139776393487936> sf ---> option name Threads type spin default 1 min 1 max 1024
[Engine] [18:12:39.244277] <139776393487936> sf ---> option name Hash type spin default 16 min 1 max 33554432
[Engine] [18:12:39.244283] <139776393487936> sf ---> option name Clear Hash type button
[Engine] [18:12:39.244289] <139776393487936> sf ---> option name Ponder type check default false
[Engine] [18:12:39.244296] <139776393487936> sf ---> option name MultiPV type spin default 1 min 1 max 256
[Engine] [18:12:39.244302] <139776393487936> sf ---> option name Skill Level type spin default 20 min 0 max 20
[Engine] [18:12:39.244314] <139776393487936> sf ---> option name Move Overhead type spin default 10 min 0 max 5000
[Engine] [18:12:39.244320] <139776393487936> sf ---> option name nodestime type spin default 0 min 0 max 10000
[Engine] [18:12:39.244327] <139776393487936> sf ---> option name UCI_Chess960 type check default false
[Engine] [18:12:39.244333] <139776393487936> sf ---> option name UCI_LimitStrength type check default false
[Engine] [18:12:39.244339] <139776393487936> sf ---> option name UCI_Elo type spin default 1320 min 1320 max 3190
[Engine] [18:12:39.244345] <139776393487936> sf ---> option name UCI_ShowWDL type check default false
[Engine] [18:12:39.244351] <139776393487936> sf ---> option name SyzygyPath type string default <empty>
[Engine] [18:12:39.244358] <139776393487936> sf ---> option name SyzygyProbeDepth type spin default 1 min 1 max 100
[Engine] [18:12:39.244364] <139776393487936> sf ---> option name Syzygy50MoveRule type check default true
[Engine] [18:12:39.244370] <139776393487936> sf ---> option name SyzygyProbeLimit type spin default 7 min 0 max 7
[Engine] [18:12:39.244376] <139776393487936> sf ---> option name EvalFile type string default nn-ddcfb9224cdb.nnue
[Engine] [18:12:39.244382] <139776393487936> sf ---> option name EvalFileSmall type string default nn-37f18f62d772.nnue
[Engine] [18:12:39.244388] <139776393487936> sf ---> uciok
[Engine] [18:12:39.009478] <139776393487936> sf ---> Stockfish dev-20240705-2cbc20e8 by the Stockfish developers (see AUTHORS file)
[Engine] [18:12:39.244213] <139776393487936> sf ---> id name Stockfish dev-20240705-2cbc20e8
[Engine] [18:12:39.244250] <139776393487936> sf ---> id author the Stockfish developers (see AUTHORS file)
[Engine] [18:12:39.244257] <139776393487936> sf ---> option name Debug Log File type string default 
[Engine] [18:12:39.244263] <139776393487936> sf ---> option name NumaPolicy type string default auto
[Engine] [18:12:39.244270] <139776393487936> sf ---> option name Threads type spin default 1 min 1 max 1024
[Engine] [18:12:39.244276] <139776393487936> sf ---> option name Hash type spin default 16 min 1 max 33554432
[Engine] [18:12:39.244282] <139776393487936> sf ---> option name Clear Hash type button
[Engine] [18:12:39.244288] <139776393487936> sf ---> option name Ponder type check default false
[Engine] [18:12:39.244294] <139776393487936> sf ---> option name MultiPV type spin default 1 min 1 max 256
[Engine] [18:12:39.244300] <139776393487936> sf ---> option name Skill Level type spin default 20 min 0 max 20
[Engine] [18:12:39.244307] <139776393487936> sf ---> option name Move Overhead type spin default 10 min 0 max 5000
[Engine] [18:12:39.244319] <139776393487936> sf ---> option name nodestime type spin default 0 min 0 max 10000
[Engine] [18:12:39.244325] <139776393487936> sf ---> option name UCI_Chess960 type check default false
[Engine] [18:12:39.244332] <139776393487936> sf ---> option name UCI_LimitStrength type check default false
[Engine] [18:12:39.244338] <139776393487936> sf ---> option name UCI_Elo type spin default 1320 min 1320 max 3190
[Engine] [18:12:39.244344] <139776393487936> sf ---> option name UCI_ShowWDL type check default false
[Engine] [18:12:39.244350] <139776393487936> sf ---> option name SyzygyPath type string default <empty>
[Engine] [18:12:39.244356] <139776393487936> sf ---> option name SyzygyProbeDepth type spin default 1 min 1 max 100
[Engine] [18:12:39.244362] <139776393487936> sf ---> option name Syzygy50MoveRule type check default true
[Engine] [18:12:39.244369] <139776393487936> sf ---> option name SyzygyProbeLimit type spin default 7 min 0 max 7
[Engine] [18:12:39.244375] <139776393487936> sf ---> option name EvalFile type string default nn-ddcfb9224cdb.nnue
[Engine] [18:12:39.244381] <139776393487936> sf ---> option name EvalFileSmall type string default nn-37f18f62d772.nnue
[Engine] [18:12:39.244387] <139776393487936> sf ---> uciok
[TRACE ] [18:12:39.244552] <139776393487936> fastchess --- Sending ucinewgame to engine sf
[Engine] [18:12:39.244558] <139776393487936> sf <--- ucinewgame
[TRACE ] [18:12:39.244575] <139776393487936> fastchess --- Pinging engine sf
[Engine] [18:12:39.244581] <139776393487936> sf <--- isready
[Engine] [18:12:39.247221] <139776393487936> sf ---> readyok
[Engine] [18:12:39.247207] <139776393487936> sf ---> readyok
[TRACE ] [18:12:39.247254] <139776393487936> fastchess --- Engine sf is responsive.
[TRACE ] [18:12:39.247261] <139776393487936> fastchess --- Sending ucinewgame to engine sf
[Engine] [18:12:39.247267] <139776393487936> sf <--- ucinewgame
[TRACE ] [18:12:39.247283] <139776393487936> fastchess --- Pinging engine sf
[Engine] [18:12:39.247289] <139776393487936> sf <--- isready
[Engine] [18:12:39.249790] <139776393487936> sf ---> readyok
[Engine] [18:12:39.249776] <139776393487936> sf ---> readyok
[TRACE ] [18:12:39.249820] <139776393487936> fastchess --- Engine sf is responsive.
[TRACE ] [18:12:39.249827] <139776393487936> fastchess --- Refreshing engine cdb2uci
[TRACE ] [18:12:39.249837] <139776393487936> fastchess --- Starting engine cdb2uci at ../cdblib/cdb2uci.sh
[TRACE ] [18:12:39.250003] <139776393487936> fastchess --- Sending uci to engine cdb2uci
[Engine] [18:12:39.250023] <139776393487936> cdb2uci <--- uci
[TRACE ] [18:12:39.250035] <139776393487936> fastchess --- Waiting for uciok from engine cdb2uci
[TRACE ] [18:12:39.250439] <fastchess> Playing game 2 between cdb2uci and sf
[TRACE ] [18:12:39.250511] <139776393487936> fastchess --- Refreshing engine cdb2uci
[TRACE ] [18:12:39.250526] <139776393487936> fastchess --- Starting engine cdb2uci at ../cdblib/cdb2uci.sh
[Engine] [18:12:39.250541] <139776393487936> cdb2uci ---> Started game 2 of 2 (cdb2uci vs sf)
[TRACE ] [18:12:39.250664] <139776393487936> fastchess --- Sending uci to engine cdb2uci
[Engine] [18:12:39.250679] <139776393487936> cdb2uci <--- uci
[TRACE ] [18:12:39.250697] <139776393487936> fastchess --- Waiting for uciok from engine cdb2uci
```

so fast-chess thinks the engine is not responding. Do you know why? Also, the logs mention `Playing game 2 between cdb2uci and weiss` way before stdout sees game 2 starting. And for game 1 nothing is reported on console or in log. Moreover, the logs say `Started game 2 of 2 (cdb2uci vs sf)` twice, but never for game 1.

**Comment by robertnurnberg** [comment]
Ok, thanks to @disservin for pointing out a fix: https://github.com/Disservin/fast-chess/issues/614#issuecomment-2241249624.
So with 
```
#! /bin/bash

python $HOME/git/cdblib/cdb2uci.py -c 1 -ee
```

I get some games. But fast-chess complains about missing bestmoves: 
```
[Engine] [20:28:32.360747] <140120305956416> cdb2uci ---> info depth 1 seldepth 1 multipv 1 score cp 0 time 10609 nodes 20 nps 2 pv b8c6
[Engine] [20:28:32.360822] <140120305956416> cdb2uci ---> bestmove b8c6
[Engine] [20:28:32.360845] <140120305956416> cdb2uci ---> readyok
[Engine] [20:28:32.360712] <140120305956416> cdb2uci ---> info depth 1 seldepth 1 multipv 1 score cp 0 time 10609 nodes 20 nps 2 pv b8c6
[Engine] [20:28:32.360817] <140120305956416> cdb2uci ---> bestmove b8c6
[Engine] [20:28:32.360840] <140120305956416> cdb2uci ---> readyok
[TRACE ] [20:28:32.360899] <140120305956416> fastchess --- Engine cdb2uci is responsive.
[WARN  ] [20:28:32.360976] <140120305956416> fastchess --- Warning; No bestmove found in the last line from cdb2uci
[WARN  ] [20:28:32.361017] <140120305956416> fastchess --- Warning; No bestmove found in the last line from cdb2uci
[WARN  ] [20:28:32.361067] <140120305956416> fastchess --- Warning; Engine cdb2uci loses on time
[Engine] [20:28:32.361109] <140120305956416> cdb2uci <--- stop
```
So if I read this correctly, fast-chess asks fora `readyok` from engine, but then wants to read `bestmove` again?

**Comment by Disservin** [comment]
> So if I read this correctly, fast-chess asks fora `readyok` from engine, but then wants to read `bestmove` again?

yeah after finishing to read from the engine, fc sends a isready to check if the engine is alive or crashed and then continues with extracting the bestmove

**Comment by robertnurnberg** [comment]
> > So if I read this correctly, fast-chess asks fora `readyok` from engine, but then wants to read `bestmove` again?
> 
> yeah after finishing to read from the engine, fc sends a isready to check if the engine is alive or crashed and then continues with extracting the bestmove

Hm, is that covered by the specs? That engine must repeat bestmove after each isready? Just wondering if there could be other engines out there that would fall foul of that.

**Comment by robertnurnberg** [comment]
Hm, in interactive mode I can see no difference between how stockfish reacts to 

```
go depth 5
isready
```

and how the python engine reacts.

**Comment by gahtan-syarif** [comment]
it doesnt have to repeat the bestmove after each isready, what disservin meant is fastchess would first send isready before extracting the bestmove information
an example comujnication between an engine an fc for each move looks like this
```
[Engine] [02:35:00.034357] <  2> Engine1 <--- isready
[Engine] [02:35:00.034836] <  2> Engine1 ---> readyok
[Engine] [02:35:00.034836] <  2> Engine1 ---> readyok
[Engine] [02:35:00.034987] <  2> Engine1 <--- position fen rn2k2r/pppq1ppp/3b1n2/3p4/3P4/3QPN2/PPP2PPP/RNB1K2R b KQkq - 2 8 moves b8c6 e1g1 g7g5 c2c4 g5g4
[Engine] [02:35:00.035055] <  2> Engine1 <--- isready
[Engine] [02:35:00.035512] <  2> Engine1 ---> readyok
[Engine] [02:35:00.035512] <  2> Engine1 ---> readyok
[Engine] [02:35:00.035665] <  2> Engine1 <--- go wtime 968 btime 930 winc 10 binc 10
[Engine] [02:35:00.036266] <  2> Engine1 ---> info string Available processors: 0-7
[Engine] [02:35:00.036306] <  2> Engine1 ---> info string Using 1 thread
[Engine] [02:35:00.036324] <  2> Engine1 ---> info string NNUE evaluation using nn-e8bac1c07a5a.nnue (133MiB, (22528, 3072, 15, 32, 1))
[Engine] [02:35:00.036342] <  2> Engine1 ---> info string NNUE evaluation using nn-37f18f62d772.nnue (6MiB, (22528, 128, 15, 32, 1))
[Engine] [02:35:00.036888] <  2> Engine1 ---> info depth 1 seldepth 7 multipv 1 score cp 98 nodes 60 nps 30000 hashfull 0 tbhits 0 time 2 pv f3h4 d5c4
[Engine] [02:35:00.036931] <  2> Engine1 ---> info depth 2 seldepth 6 multipv 1 score cp 98 nodes 98 nps 49000 hashfull 0 tbhits 0 time 2 pv f3h4 d5c4 d3c4
[Engine] [02:35:00.036950] <  2> Engine1 ---> info depth 3 seldepth 6 multipv 1 score cp 98 nodes 138 nps 69000 hashfull 0 tbhits 0 time 2 pv f3h4 d5c4 d3c4 e8c8
[Engine] [02:35:00.036996] <  2> Engine1 ---> info depth 4 seldepth 9 multipv 1 score cp 109 nodes 230 nps 115000 hashfull 0 tbhits 0 time 2 pv f3h4 d5c4
[Engine] [02:35:00.037166] <  2> Engine1 ---> info depth 5 seldepth 6 multipv 1 score cp 104 nodes 324 nps 162000 hashfull 0 tbhits 0 time 2 pv f3h4 c6b4 d3b3 d5c4 b3c4
[Engine] [02:35:00.037206] <  2> Engine1 ---> info depth 6 seldepth 6 multipv 1 score cp 104 nodes 377 nps 188500 hashfull 0 tbhits 0 time 2 pv f3h4 c6b4 d3b3 d5c4 b3c4
[Engine] [02:35:00.037977] <  2> Engine1 ---> info depth 7 seldepth 8 multipv 1 score cp 110 nodes 822 nps 274000 hashfull 0 tbhits 0 time 3 pv f3h4 d5c4 d3c4 c6e7 b1c3 e7g6
[Engine] [02:35:00.039758] <  2> Engine1 ---> info depth 8 seldepth 11 multipv 1 score cp 115 nodes 2116 nps 423200 hashfull 0 tbhits 0 time 5 pv f3h4 e8c8 b1c3 d5c4
[Engine] [02:35:00.041199] <  2> Engine1 ---> info depth 9 seldepth 10 multipv 1 score cp 113 nodes 3236 nps 539333 hashfull 0 tbhits 0 time 6 pv f3h4 c6b4 d3b3 d5c4 b3c4 e8c8 b1c3 b4c2
[Engine] [02:35:00.042287] <  2> Engine1 ---> info depth 10 seldepth 11 multipv 1 score cp 106 nodes 3974 nps 567714 hashfull 1 tbhits 0 time 7 pv f3h4 e8c8 b1c3 d5c4 d3c4 d7e6 c4b5
[Engine] [02:35:00.042338] <  2> Engine1 ---> bestmove f3h4 ponder e8c8
[Engine] [02:35:00.042617] <  2> Engine1 <--- isready
[Engine] [02:35:00.043172] <  2> Engine1 ---> readyok
[Engine] [02:35:00.043172] <  2> Engine1 ---> readyok
```
(ignore the readyok being printed twice)

**Comment by robertnurnberg** [comment]
Right. So if I do this command sequence by hand in the interactive shell, my ptyhon engines responds in the same way as in your example. Yet fc cannot extract bestmove somehow.

**Comment by robertnurnberg** [comment]
Ok, with cute-chess the engine seems to work fine:
```
./cutechess-cli -engine cmd=../../stockfish/src/stockfish name=sf tc=1+0.1 -engine cmd=../../cdblib/cdb2uci.sh name=cdb2uci tc=10+5 -each proto=uci -concurrency 1 -openings file=grob.epd -rounds 2 -games 1 -pgnout file=grob_sf_cdb2uci.pgn -debug
<snip>
19660 <sf(0): bestmove c3e2 ponder g8h7
19661 >cdb2uci(1): position startpos moves e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 d2d3 f8c5 b1c3 e8g8 a2a3 a7a5 c1g5 h7h6 g5h4 c5e7 h2h3 d7d6 e1g1 g7g5 h4g3 g5g4 h3g4 c8g4 c3e2
19661 >cdb2uci(1): isready
19661 <cdb2uci(1): readyok
19662 >cdb2uci(1): go wtime 761 btime 57267 winc 100 binc 5000
20114 <cdb2uci(1): info depth 1 seldepth 1 multipv 1 score cp 20 time 452 nodes 1 nps 2 pv g8h7
20114 <cdb2uci(1): bestmove g8h7
20115 >sf(0): position startpos moves e2e4 e7e5 g1f3 b8c6 f1c4 g8f6 d2d3 f8c5 b1c3 e8g8 a2a3 a7a5 c1g5 h7h6 g5h4 c5e7 h2h3 d7d6 e1g1 g7g5 h4g3 g5g4 h3g4 c8g4 c3e2 g8h7
20115 >sf(0): isready
20116 <sf(0): readyok
```

**Comment by robertnurnberg** [comment]
More testing with a "dumb" version of the engine:
```
#! /bin/bash

python $HOME/git/cdblib/cdb2uci.py -c 1
```
(so this one does not wait for eval of unscored positions, essentially playing randomly once out of cdb book).

```
> ./cutechess-cli -engine cmd=../../stockfish/src/stockfish name=sf tc=1+0.1 -engine cmd=../../cdblib/dumb2uci.sh name=cdb2uci tc=10+5 -each proto=uci -concurrency 10 -openings file=grob.epd -rounds 10 -games 2
Started game 3 of 20 (sf vs cdb2uci)
Started game 6 of 20 (cdb2uci vs sf)
Started game 1 of 20 (sf vs cdb2uci)
Started game 2 of 20 (cdb2uci vs sf)
Started game 5 of 20 (sf vs cdb2uci)
Started game 4 of 20 (cdb2uci vs sf)
Started game 7 of 20 (sf vs cdb2uci)
Started game 8 of 20 (cdb2uci vs sf)
Started game 9 of 20 (sf vs cdb2uci)
Started game 10 of 20 (cdb2uci vs sf)
Finished game 2 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 1 - 0 - 0  [1.000] 1
Started game 11 of 20 (sf vs cdb2uci)
Finished game 10 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 2 - 0 - 0  [1.000] 2
Started game 12 of 20 (cdb2uci vs sf)
Finished game 1 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 3 - 0 - 0  [1.000] 3
Started game 13 of 20 (sf vs cdb2uci)
Finished game 4 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 4 - 0 - 0  [1.000] 4
Started game 14 of 20 (cdb2uci vs sf)
Finished game 8 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 5 - 0 - 0  [1.000] 5
Started game 15 of 20 (sf vs cdb2uci)
Finished game 6 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 6 - 0 - 0  [1.000] 6
Started game 16 of 20 (cdb2uci vs sf)
Finished game 7 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 7 - 0 - 0  [1.000] 7
Started game 17 of 20 (sf vs cdb2uci)
Finished game 3 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 8 - 0 - 0  [1.000] 8
Started game 18 of 20 (cdb2uci vs sf)
Finished game 9 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 9 - 0 - 0  [1.000] 9
Started game 19 of 20 (sf vs cdb2uci)
Finished game 5 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 10 - 0 - 0  [1.000] 10
Started game 20 of 20 (cdb2uci vs sf)
Finished game 11 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 11 - 0 - 0  [1.000] 11
Finished game 12 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 12 - 0 - 0  [1.000] 12
Finished game 14 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 13 - 0 - 0  [1.000] 13
Finished game 13 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 14 - 0 - 0  [1.000] 14
Finished game 16 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 15 - 0 - 0  [1.000] 15
Finished game 20 (cdb2uci vs sf): 1/2-1/2 {Draw by 3-fold repetition}
Score of sf vs cdb2uci: 15 - 0 - 1  [0.969] 16
Finished game 15 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 16 - 0 - 1  [0.971] 17
Finished game 18 (cdb2uci vs sf): 0-1 {Black mates}
Score of sf vs cdb2uci: 17 - 0 - 1  [0.972] 18
Finished game 17 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 18 - 0 - 1  [0.974] 19
Finished game 19 (sf vs cdb2uci): 1-0 {White mates}
Score of sf vs cdb2uci: 19 - 0 - 1  [0.975] 20
...      sf playing White: 10 - 0 - 0  [1.000] 10
...      sf playing Black: 9 - 0 - 1  [0.950] 10
...      White vs Black: 10 - 9 - 1  [0.525] 20
Elo difference: 636.4 +/- nan, LOS: 100.0 %, DrawRatio: 5.0 %
SPRT: llr 0 (0.0%), lbound -inf, ubound inf

Player: sf
   "Draw by 3-fold repetition": 1
   "Win: Black mates": 9
   "Win: White mates": 10
Player: cdb2uci
   "Draw by 3-fold repetition": 1
   "Loss: Black mates": 9
   "Loss: White mates": 10
Finished match
```

**Comment by robertnurnberg** [comment]
Testing with normal version of the engine: 
```
#! /bin/bash

python $HOME/git/cdblib/cdb2uci.py -c 1 -ee
```

```
> ./cutechess-cli -engine cmd=../../stockfish/src/stockfish name=sf tc=1+0.1 -engine cmd=../../cdblib/cdb2uci.sh name=cdb2uci tc=3600+10 -each proto=uci -concurrency 64 -openings file=grob.epd -rounds 64 -games 2 -pgnout file=grob_sf_cdb2uci.pgn
<snip>
Player: sf
   "Draw by 3-fold repetition": 59
   "Draw by fifty moves rule": 2
   "Draw by insufficient mating material": 6
   "Draw by stalemate": 3
   "Loss: Black mates": 23
   "Loss: White mates": 9
   "No result": 24
   "Win: Black loses on time": 1
   "Win: Black's connection stalls": 1
Player: cdb2uci
   "Draw by 3-fold repetition": 59
   "Draw by fifty moves rule": 2
   "Draw by insufficient mating material": 6
   "Draw by stalemate": 3
   "Loss: Black loses on time": 1
   "Loss: Black's connection stalls": 1
   "No result": 24
   "Win: Black mates": 23
   "Win: White mates": 9
Finished match
```

So against sf on 1+0.1 the only losses are losses on time. :)

**Pull request merged**
